[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firebase-admin>=6.9.0",
    "flask>=3.1.1",
    "langchain>=0.3.26",
    "torch>=2.7.1",
    "transformers>=4.53.1",
]
