name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & UX
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  fl_chart: ^0.63.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  firebase_database: ^10.5.4
  cloud_firestore: ^4.15.4  # ✅ You are using Firestore in signup

  # Validation and AI
  email_validator: ^2.1.17
  flutter_gemini: ^3.0.0

  # Maps and config
  flutter_map: ^6.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
