// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQTEjHrFvoYLz-NM8WB4EPlYFkKTzGq2Y',
    appId: '1:536188765571:web:cd3d92a62a5f16af4422b6',
    messagingSenderId: '536188765571',
    projectId: 'cchack-f45bf',
    authDomain: 'cchack-f45bf.firebaseapp.com',
    storageBucket: 'cchack-f45bf.firebasestorage.app',
    measurementId: 'G-WX0TPG7PYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8_-TVA1SY-1en7jBMhrWRYc6ZX7EdqXg',
    appId: '1:536188765571:android:6c25ac99bf2e8b0c4422b6',
    messagingSenderId: '536188765571',
    projectId: 'cchack-f45bf',
    storageBucket: 'cchack-f45bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ7YwKn8dTK8D1adiE34f_Lo3CHUTc0Os',
    appId: '1:536188765571:ios:1d9aa92b63cde78f4422b6',
    messagingSenderId: '536188765571',
    projectId: 'cchack-f45bf',
    storageBucket: 'cchack-f45bf.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ7YwKn8dTK8D1adiE34f_Lo3CHUTc0Os',
    appId: '1:536188765571:ios:1d9aa92b63cde78f4422b6',
    messagingSenderId: '536188765571',
    projectId: 'cchack-f45bf',
    storageBucket: 'cchack-f45bf.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQTEjHrFvoYLz-NM8WB4EPlYFkKTzGq2Y',
    appId: '1:536188765571:web:40c88953155728d24422b6',
    messagingSenderId: '536188765571',
    projectId: 'cchack-f45bf',
    authDomain: 'cchack-f45bf.firebaseapp.com',
    storageBucket: 'cchack-f45bf.firebasestorage.app',
    measurementId: 'G-7WPSN1KWY0',
  );
}
